### ISSUE TITLE
the github.com/webtor-io/abuse-store repository does not exist

### ISSUE THREAD

**Issue by rgl** [webtor-io/torrent-store#1]
The commit at https://github.com/webtor-io/torrent-store/commit/0c0fef86d404723c7315da494212c139ffa3c936 renamed the package bitbucket.org/vintikzzzz/abuse-store to github.com/webtor-io/abuse-store, but it seems you forgot to create the github.com/webtor-io/abuse-store repository? without that repository, and without the `vendor` directory, `go mod tidy` fails. I'm trying to remove all `vendor` directories, as they are not really needed since go has a global module repository.

**Comment by vintikzzz** [comment]
`abuse-store` is a private repository, it currently stores some google credentials and I haven't found time to fix this.
That's why it was [vendored](https://github.com/webtor-io/torrent-store/tree/master/vendor/github.com/webtor-io/abuse-store/abuse-store)

**Comment by vintikzzz** [comment]
https://github.com/webtor-io/abuse-store now is finally public
